### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by zorosmith** [jcbrenes/Planta-SerialDynamixel#1]
Hello! I have bought some FSRs , a SHARP sensor ,a 74LS241 and an arduino nano to complete  this project. And now I'm confused with several questions. Any help will be appreciate!

1. How to link all the sensors to the arduino nano. Do you have any demo about this? 
2. In your arduino code, after you check the dynamixel data frame, you will check the id. And I am confused with why are you able to get the id from serial buffer?

**Comment by jcbrenes** [comment]
Hi! Nice to see you are getting into this project! Regarding your questions:

1- I connected the FSR sensors to the Arduino using a Voltage divider
configuration. I based on this Adafruit tutorial:
https://learn.adafruit.com/force-sensitive-resistor-fsr/using-an-fsr

2- I don´t exactly understand your question. When the master (the BBB
board) sends a message to the Dynamixel bus, all devices hear it, so the
data frame includes the ID, so only the required device will answer (the
foot in this case).

Hope this answers your doubts.

JC

**Comment by zorosmith** [comment]
Hello, I am appreciative of your answer! Regarding your answers:
1- I connected the FSR sensors following the Adafruit tutorial, as well as the code. However, when I squeeze the sensor, I was not able to get precise results. 
When I squeezed lightly , the output of the FSR would be very big  and increase  quickly. Thus, the output is several times the input. When I squeezed hard, it increases slowly, and the output get closed to the input gradually.
Did you meet with this trouble, could you share me your solution?

2- Your answer has solved my question! Thx！

**Comment by jcbrenes** [comment]
Sorry for the delay. I didn´t have that problem you described when I
implemented the circuit. Perhaps you can try switching positions between
the FSR and the resistance on the voltage divider, this way you can
change if you want a small voltage value when high pressure occurs or the
opposite.

Hope this helps.
